### ISSUE TITLE
Reverse change log order

### ISSUE THREAD

**Issue by nilshoerrmann** [medienbaecker/nova-kirby-snippets#2]
A minor thing I just noticed while checking for updates in the extension panel: 

It would be a good idea to reverse the order of entries in the change log with latest versions comming first. This way, users could spot the latest changes easily. Currently, the newer releases are hidden "below the fold" (if that's still a term these days).

**Comment by medienbaecker** [comment]
Thanks for the suggestion, that makes sense. I just added a few new icon completions and reversed the changelog 👍

**Comment by nilshoerrmann** [comment]
Cool, thanks!
